feat: issue api for self-issued JWT credentials
trustbloc/wallet-sdk pull request #125
Opened 2022-12-20 23:32 UTC by Moopli

Signed-off-by: Filip Burlacu <filip.burlacu@securekey.com>

2022-12-21 14:59 UTC, vkubiv approved these changes

2022-12-21 15:08 UTC, rolsonquadras approved these changes

2022-12-21 15:10 UTC, sudeshrshetty requested changes
- make it credential format agnostic
- this API should be in credential signer API as `issue()` function

2023-01-17 14:42 UTC, sudeshrshetty approved these changes

2023-01-17 14:42 UTC, merged