Fix the error screen popping up while handling the redirect to show credential preview - auth flow
trustbloc/wallet-sdk pull request #484
Opened 2023-07-13 07:29 UTC by talwinder50

2023-07-13 13:55 UTC, DRK3 commented on demo/app/android/app/src/androidTest/kotlin/integration_test.kt
> +        val requiredOpenID4CIArgs = InteractionArgs(requestURI, crypto, didResolver)
`InteractionArgs` and `Interaction`are deprecated - `IssuerInitiatedInteractionArgs` and `IssuerInteraction` should continue to be used. Is there a reason you switched these back?

2023-07-13 14:13 UTC, DRK3 commented on demo/app/android/app/src/androidTest/kotlin/integration_test.kt
> +            var registrationResp = Oauth2.registerClient(dynamicRegistrationEndpoint, clientMetadata, null)
You'll want to pass through the scopes from the response like I did in my latest PR (just merged in)

2023-07-13 17:55 UTC, DRK3 requested changes
See my comments

2023-07-14 12:47 UTC, birtony approved these changes

2023-07-14 13:16 UTC, vkubiv approved these changes

2023-07-14 13:31 UTC, merged